vim.cmd("language en_US")
require("darek.plugins-setup")
require("darek.core.options")
require("darek.core.keymaps")
require("darek.core.colorscheme")
require("darek.plugins.comment")
require("darek.plugins.nvim-tree")
require("darek.plugins.lualine")
require("darek.plugins.telescope")
require("darek.plugins.nvim-cmp")
require("darek.plugins.lsp.mason")
require("darek.plugins.lsp.lspsaga")
require("darek.plugins.lsp.lspconfig")
require("darek.plugins.lsp.null-ls")
require("darek.plugins.autopairs")
require("darek.plugins.treesitter")
require("darek.plugins.gitsigns")
